### ISSUE TITLE
쓰지 않는 MongoDB collection 제거 작업

### ISSUE THREAD

**Issue by JoMingyu** [DSM-DMS/DMS-Backend#2]
Live로 돌고 있는 서버가 참조하는 'dms' 데이터베이스의 컬렉션 중, 이전에는 사용하다가 데이터베이스 구조를 바꾸며 현재는 쓸모 없는(CRUD가 진행되지 않는) 컬렉션이 있습니다. 제거 작업이 필요합니다.

**Comment by RISMME** [comment]
한번 소스를 읽어보니 쓰이지 않는 컬렉션이 딱히 안보이네요 예를 들어 어떤 컬렉션이 사용되지 않고 있나요?

**Comment by JoMingyu** [comment]
딱 봐도 이상한 놈들 몇가지 있습니다. meal과 meal_model이 같이 있고, report_base와 report_model이 같이 있습니다.

**Comment by RISMME** [comment]
meal_model과 report_model 외에 불필요한 컬렉션이 없음을 확인하였고, 불필요한 컬렉션을 drop으로 확 떨궈버려따! 행보캤다!

**Comment by JoMingyu** [comment]
ㄷㄷ;
